name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ChaosMachine.sln
      - name: Build
        run: dotnet build ChaosMachine.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test ChaosMachine.sln --configuration Release --no-build --collect:"XPlat Code Coverage"
      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ChaosMachine/bin/Release/net8.0/
            ChaosMachine.Tests/bin/Release/net8.0/
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ChaosMachine.Tests/TestResults/
      - name: Publish Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ChaosMachine.Tests/TestResults/**/*.xml
